# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_version = 3.7
artifact_minecraft_version = 1.19.4

minecraft_version = 1.19.4
forge_version = 45.2.6

forgegradle_version = 6.0.7
mixingradle_version = 0.7-SNAPSHOT
mixin_version = 0.8.5
librarian_version = 1.+
cursegradle_version = 1.4.0
parchment_version = 2023.06.26

flywheel_minecraft_version = 1.19.3
flywheel_version = 0.6.9-2